package com.freebuds.controller.protocol

enum class HuaweiCapability(
    val displayName: String,
    val description: String
) {
    BATTERY("Battery", "Read battery level (global, L/R, case)"),
    BATTERY_TWS("Battery TWS", "Read L/R/case individual battery"),
    INFO("Device Info", "Read device name, model, firmware version"),
    ANC("ANC", "Read/write noise control mode"),
    ANC_LEVEL("ANC Level", "Support cancel level settings"),
    ANC_DYNAMIC("ANC Dynamic", "Support dynamic ANC adjustment"),
    VOICE_BOOST("Voice Boost", "Support voice boost mode"),
    IN_EAR("In-Ear Detection", "Read wear/remove state"),
    ACTION_DOUBLE_TAP("Double Tap", "Read/write double tap action (L/R)"),
    ACTION_DOUBLE_TAP_IN_CALL("Double Tap In-Call", "Double tap action during call"),
    ACTION_TRIPLE_TAP("Triple Tap", "Read/write triple tap action"),
    ACTION_LONG_TAP("Long Tap", "Read/write long tap action (basic)"),
    ACTION_LONG_TAP_SPLIT("Long Tap Split", "Read/write long tap action (L/R separately)"),
    ACTION_LONG_TAP_SPLIT_ANC("Long Tap Split ANC", "Long tap ANC side channel"),
    ACTION_LONG_TAP_RIGHT("Long Tap Right", "Long tap right side support"),
    ACTION_LONG_TAP_EXTRA("Long Tap Extra", "Extra long tap options"),
    ACTION_LONG_TAP_IN_CALL("Long Tap In-Call", "Long tap behavior during call"),
    ACTION_SWIPE("Swipe Gesture", "Read/write swipe gesture"),
    ACTION_POWER_BUTTON("Power Button", "Read/write power button action"),
    AUTO_PAUSE("Auto Pause", "Read/write auto pause config"),
    EQ_PRESET("EQ Preset", "Read/write equalizer preset"),
    EQ_CUSTOM("EQ Custom", "Support custom EQ"),
    EQ_FAKE_BUILTIN("EQ Fake Built-in", "Fake built-in preset for compatibility"),
    DUAL_CONNECT("Dual Connect", "Read/write dual device connect"),
    DUAL_CONNECT_AUTO("Dual Auto Connect", "Auto reconnect on dual connect"),
    LOW_LATENCY("Low Latency", "Read/write low latency / gaming mode"),
    SOUND_QUALITY("Sound Quality", "Sound quality preference"),
    VOICE_LANGUAGE("Voice Language", "Read/write voice prompt language"),
    LOGS("Logs", "Device debugging logs"),
    ANC_LEGACY("ANC Legacy", "Legacy ANC change protocol"),
    WEAR_DETECT("Wear Detect", "Wear detection state"),
}

enum class HuaweiModel(
    val displayName: String,
    val sppPort: Int = 16,
    val hasTwsBattery: Boolean = true,
) {
    BUDS_4I("HUAWEI FreeBuds 4i / HONOR Earbuds 2/2 Lite/SE"),
    BUDS_5I("HUAWEI FreeBuds 5i"),
    BUDS_6I("HUAWEI FreeBuds 6i", sppPort = 1),
    BUDS_7I("HUAWEI FreeBuds 7i", sppPort = 1),
    BUDS_PRO("HUAWEI FreeBuds Pro", sppPort = 1),
    BUDS_PRO_2("HUAWEI FreeBuds Pro 2", sppPort = 1),
    BUDS_PRO_3("HUAWEI FreeBuds Pro 3 / Pro 4 / FreeClip", sppPort = 1),
    BUDS_SE("HUAWEI FreeBuds SE"),
    BUDS_SE_2("HUAWEI FreeBuds SE 2", sppPort = 1),
    BUDS_SE_4("HUAWEI FreeBuds SE 4", sppPort = 1),
    STUDIO("HUAWEI FreeBuds Studio", sppPort = 1, hasTwsBattery = false),
    LACE_PRO("HUAWEI FreeLace Pro", sppPort = 1, hasTwsBattery = true),
    LACE_PRO_2("HUAWEI FreeLace Pro 2", sppPort = 1, hasTwsBattery = false),
}

val modelCapabilities: Map<HuaweiModel, List<HuaweiCapability>> = mapOf(
    HuaweiModel.BUDS_4I to listOf(
        HuaweiCapability.LOGS,
        HuaweiCapability.INFO,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.ANC,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ACTION_DOUBLE_TAP,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.AUTO_PAUSE,
        HuaweiCapability.VOICE_LANGUAGE,
    ),
    HuaweiModel.BUDS_5I to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.ACTION_DOUBLE_TAP,
        HuaweiCapability.ACTION_DOUBLE_TAP_IN_CALL,
        HuaweiCapability.ACTION_TRIPLE_TAP,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.ACTION_SWIPE,
        HuaweiCapability.AUTO_PAUSE,
        HuaweiCapability.SOUND_QUALITY,
        HuaweiCapability.LOW_LATENCY,
        HuaweiCapability.EQ_PRESET,
        HuaweiCapability.VOICE_LANGUAGE,
        HuaweiCapability.DUAL_CONNECT,
    ),
    HuaweiModel.BUDS_6I to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.ACTION_DOUBLE_TAP,
        HuaweiCapability.ACTION_DOUBLE_TAP_IN_CALL,
        HuaweiCapability.ACTION_TRIPLE_TAP,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.ACTION_SWIPE,
        HuaweiCapability.AUTO_PAUSE,
        HuaweiCapability.SOUND_QUALITY,
        HuaweiCapability.LOW_LATENCY,
        HuaweiCapability.EQ_PRESET,
        HuaweiCapability.EQ_FAKE_BUILTIN,
        HuaweiCapability.EQ_CUSTOM,
        HuaweiCapability.VOICE_LANGUAGE,
        HuaweiCapability.DUAL_CONNECT,
    ),
    // Temporary conservative profile for FreeBuds 7i.
    // Full 7i adaptation is planned for the next major compatibility round.
    HuaweiModel.BUDS_7I to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.ACTION_TRIPLE_TAP,
        HuaweiCapability.SOUND_QUALITY,
        HuaweiCapability.LOW_LATENCY,
        HuaweiCapability.VOICE_LANGUAGE,
    ),
    HuaweiModel.BUDS_PRO to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.VOICE_BOOST,
        HuaweiCapability.ACTION_SWIPE,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.VOICE_LANGUAGE,
        HuaweiCapability.DUAL_CONNECT,
    ),
    HuaweiModel.BUDS_PRO_2 to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.ACTION_SWIPE,
        HuaweiCapability.AUTO_PAUSE,
        HuaweiCapability.SOUND_QUALITY,
        HuaweiCapability.EQ_PRESET,
        HuaweiCapability.DUAL_CONNECT,
        HuaweiCapability.VOICE_LANGUAGE,
    ),
    HuaweiModel.BUDS_PRO_3 to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.VOICE_BOOST,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.SOUND_QUALITY,
        HuaweiCapability.EQ_PRESET,
        HuaweiCapability.EQ_CUSTOM,
        HuaweiCapability.AUTO_PAUSE,
        HuaweiCapability.DUAL_CONNECT,
        HuaweiCapability.WEAR_DETECT,
        HuaweiCapability.VOICE_LANGUAGE,
        HuaweiCapability.ACTION_DOUBLE_TAP,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.ACTION_SWIPE,
        HuaweiCapability.LOW_LATENCY,
    ),
    HuaweiModel.BUDS_SE to listOf(
        HuaweiCapability.LOGS,
        HuaweiCapability.INFO,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ACTION_DOUBLE_TAP,
    ),
    HuaweiModel.BUDS_SE_2 to listOf(
        HuaweiCapability.LOGS,
        HuaweiCapability.INFO,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ACTION_DOUBLE_TAP,
        HuaweiCapability.ACTION_DOUBLE_TAP_IN_CALL,
        HuaweiCapability.ACTION_TRIPLE_TAP,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.ACTION_LONG_TAP_IN_CALL,
        HuaweiCapability.EQ_PRESET,
        HuaweiCapability.LOW_LATENCY,
    ),
    HuaweiModel.BUDS_SE_4 to listOf(
        HuaweiCapability.LOGS,
        HuaweiCapability.INFO,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.ACTION_DOUBLE_TAP,
        HuaweiCapability.ACTION_DOUBLE_TAP_IN_CALL,
        HuaweiCapability.ACTION_TRIPLE_TAP,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.ACTION_LONG_TAP_RIGHT,
        HuaweiCapability.ACTION_LONG_TAP_EXTRA,
        HuaweiCapability.EQ_PRESET,
        HuaweiCapability.LOW_LATENCY,
    ),
    HuaweiModel.STUDIO to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.BATTERY,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.VOICE_BOOST,
        HuaweiCapability.AUTO_PAUSE,
        HuaweiCapability.EQ_PRESET,
    ),
    HuaweiModel.LACE_PRO to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.BATTERY,
        HuaweiCapability.BATTERY_TWS,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_LEGACY,
        HuaweiCapability.ACTION_POWER_BUTTON,
        HuaweiCapability.ACTION_LONG_TAP,
        HuaweiCapability.VOICE_LANGUAGE,
    ),
    HuaweiModel.LACE_PRO_2 to listOf(
        HuaweiCapability.INFO,
        HuaweiCapability.BATTERY,
        HuaweiCapability.ANC,
        HuaweiCapability.ANC_LEVEL,
        HuaweiCapability.ANC_DYNAMIC,
        HuaweiCapability.VOICE_BOOST,
        HuaweiCapability.ACTION_LONG_TAP_SPLIT,
        HuaweiCapability.VOICE_LANGUAGE,
        HuaweiCapability.EQ_CUSTOM,
        HuaweiCapability.SOUND_QUALITY,
        HuaweiCapability.LOW_LATENCY,
        HuaweiCapability.DUAL_CONNECT,
    ),
)
