package com.freebuds.controller.protocol

object HuaweiSppCommand {
    val BATTERY_READ = byteArrayOf(0x01, 0x08)
    val BATTERY_NOTIFY = byteArrayOf(0x01, 0x27)
    val AUTO_PAUSE_READ = byteArrayOf(0x2b, 0x11)
    val AUTO_PAUSE_WRITE = byteArrayOf(0x2b, 0x10)
    val DUAL_TAP_READ = byteArrayOf(0x01, 0x20)
    val DUAL_TAP_WRITE = byteArrayOf(0x01, 0x1f)
    val TRIPLE_TAP_READ = byteArrayOf(0x01, 0x26)
    val TRIPLE_TAP_WRITE = byteArrayOf(0x01, 0x25)
    val LONG_TAP_SPLIT_READ_BASE = byteArrayOf(0x2b, 0x17)
    val LONG_TAP_SPLIT_READ_ANC = byteArrayOf(0x2b, 0x19)
    val LONG_TAP_SPLIT_WRITE_BASE = byteArrayOf(0x2b, 0x16)
    val LONG_TAP_SPLIT_WRITE_ANC = byteArrayOf(0x2b, 0x18)
    val SWIPE_READ = byteArrayOf(0x2b, 0x1f)
    val SWIPE_WRITE = byteArrayOf(0x2b, 0x1e)
    val LOW_LATENCY = byteArrayOf(0x2b, 0x6c)
    val DUAL_CONNECT_ENABLED_READ = byteArrayOf(0x2b, 0x2f)
    val DUAL_CONNECT_ENABLED_WRITE = byteArrayOf(0x2b, 0x2e)
    val DUAL_CONNECT_ENUMERATE = byteArrayOf(0x2b, 0x31)
    val DUAL_CONNECT_PREFERRED_WRITE = byteArrayOf(0x2b, 0x32)
    val DUAL_CONNECT_EXECUTE = byteArrayOf(0x2b, 0x33)
    val DUAL_CONNECT_CHANGE_EVENT = byteArrayOf(0x2b, 0x36)
}
